### ISSUE TITLE
Launch file: Parameter ns is used for the namespace and frame

### ISSUE THREAD

**Issue by worldpotato** [QuanergySystems/quanergy_client_ros#14]
The parameter `ns` is used at two places. 

As namespace for the published topic:
https://github.com/QuanergySystems/quanergy_client_ros/blob/d0faad7294e4810bcf10f16b0c98b25fb3b17201/launch/client.launch#L8

and as name for the frame:
https://github.com/QuanergySystems/quanergy_client_ros/blob/d0faad7294e4810bcf10f16b0c98b25fb3b17201/launch/client.launch#L12

Sometimes it is useful to name them differently. E.g. if you have different lidar sensors and you want to group them by setting the namespaces to something like `lidar/front/quanergy1`, `lidar/front/quanergy2`, `lidar/back/quanergy3`, `lidar/back/quanergy4` and still have short frame names.

Currently this can be archived by using 
I think adding a separated parameter for the frame solves it.

**Comment by rossctaylor** [comment]
@worldpotato thanks for the issue report and PR. I made a comment on the PR that I think could satisfy what you want while keeping existing behavior.

**Comment by rossctaylor** [comment]
Merged to devel. Will release to master with the next release, hopefully in a few weeks.
