### ISSUE TITLE
Return data

### ISSUE THREAD

**Issue by HaroldMurcia** [QuanergySystems/quanergy_client_ros#20]
We are interested in to know xyzi and return  "r" of each obtained point; however point cloud does not have information about return; information is just used to filter data. ¿how can I add the information to the data sent to ROS client?

**Comment by rossctaylor** [comment]
Hi @HaroldMurcia - sorry I missed your question previously. 

We don't have this type of output right now but there are a couple ways you could get this information:

- If you choose the "all_separate_topics" option, you get a separate point cloud for each return which could then be combined however you like and the return information could be kept. 
- You could do something similar with the "all" option but you'd probably want to do it in the quanergy_client library. We use a PCL XYZIR data structure, where R is ring. You could just replace the ring value with return but if you want both, it would require quite a bit more work. Probably, the easiest way to do the replacement would be to assign `hvdir.ring` to the appropriate ring value in each of the if statements [here](https://github.com/QuanergySystems/quanergy_client/blob/master/src/parsers/data_packet_parser_00.cpp#L94).

Hope this helps.
