### ISSUE TITLE
catkin_make err

### ISSUE THREAD

**Issue by mrpanwei** [QuanergySystems/quanergy_client_ros#21]
when Processing catkin package: 'quanergy_client_ros' 
src/client_node.cpp:14:4: error: #error Incompatible Quanergy Client Version; looking for v5.x.x
how to deal with it

**Comment by rossctaylor** [comment]
Hi @mrpanwei 

Have you followed the instructions from the [Readme](https://github.com/QuanergySystems/quanergy_client_ros/blob/master/README.md)? 

You must clone two repos and use catkin_make_isolated. The instructions have all of the steps.

If you are still having issues, please let me know what OS you are using. Also, have you used a previous version or is this a brand new build?

**Comment by rossctaylor** [comment]
I'm going to close this but don't hesitate to reopen or ask additional questions if the previous comment didn't resolve the issue.
