### ISSUE TITLE
timeStamp syncronization

### ISSUE THREAD

**Issue by HaroldMurcia** [QuanergySystems/quanergy_client_ros#22]
Hi;
we have a project which uses the LiDAR M8 with an IMU. Our idea is to synchronize the rostopics by using timestamp information in ROS melodic. However in our rosbag timestamp have different values, we assume that the M8 uses its own clock.

Is there any way to configure to sync the information under the same clock?

Regards;

**Comment by rossctaylor** [comment]
By default, the sensor uses its own clock; however, it can be configured to use NTP or PPS/NMEA to synchronize with external devices. If neither of those options will work, using received time of the data on the host PC would be the best option. If you need further assistance, please contact support@quanergy.com.
