### ISSUE TITLE
all_separate_topics are the same

### ISSUE THREAD

**Issue by HaroldMurcia** [QuanergySystems/quanergy_client_ros#24]
Hi,
I'm very interested on echo information. when I choose the "all_separate_topics" option, I get 3 separate point cloud in ROStopics messages, however when I graph them they contain the **same information**.

**Comment by rossctaylor** [comment]
Hi @HaroldMurcia - the three returns do not contain exactly the same information but many of the points will be the same because there were fewer than 3 returns detected. Here is the information from the User Guide:

> The evaluation rules for assigning these labels are as follows:
>- If no return pulses are detected, each of the three return values is 0.
>- If one or more return pulses are detected:
>   - Return 0: The first return value equals Maximum.
>   - Return 1: The second return value equals Second Strongest. (But if there was only one return pulse, the return value equals Maximum.)
>   - Return 2: The third return value equals Last, which may be equal to Second Strongest or Maximum.
