### ISSUE TITLE
use_ros_time cannot be set to true

### ISSUE THREAD

**Issue by vochithanhcdt** [QuanergySystems/quanergy_client_ros#28]
I am using Quanegry M8 with Cartographer ROS but I found out that Cartographer cannot use pointcloud from M8 because M8 uses "Sensor time" instead of "ROS time". 
Even though in the "client.xml" file the "useRosTime" value is set to true, it doesn't seem to work.
I modified the file "client_node.cpp" , adding the line "ros_node_settings.use_ros_time = true;" in before line 239 and it worked.
Although it worked , I don't know where the problem was with the "client.xml" file. Please help me find the correct solution. Thank.

**Comment by rossctaylor** [comment]
Thanks for reporting this. In looking into it, I found that we had fixed this internally and neglected to release it. I've updated all the appropriate branches and created a new release. If you still see issues, let me know.
